{
    "port": 8000,

    "server_name": "AI Ethics Scenario Evaluator - LOCAL",

    "annotation_task_name": "AI Ethics Scenario Evaluation",

    "output_annotation_dir": "annotation_output/ai_ethics",
    "output_annotation_format": "tsv",
    "annotation_codebook_url": "",

    "data_files": [
       "data_files/pilot_data.csv"
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text",
    },

    "user_config": {
      "allow_all_users": True,
      "users": [],
    },

    # DISABLE PROLIFIC FOR LOCAL TESTING
    # "prolific": {
    #     "config_file_path": 'configs/prolific_config.yaml'
    # },

    "login": {
       "type": 'url_direct',    # LOCAL TESTING ONLY
       'url_argument': 'PROLIFIC_PID',
    },

    "jumping_to_id_disabled": True,
    "hide_navbar": True,

    "surveyflow": {
    "on": True,
    "order": ["pre_annotation", "post_annotation"],
    "pre_annotation": [
        "surveyflow/comprehension_check.jsonl",
        "surveyflow/instructions.jsonl", 
        "surveyflow/screener.jsonl", 
        "surveyflow/consent.jsonl"
    ],
    "post_annotation": ["surveyflow/end.jsonl"]
},

    "automatic_assignment": {
      "on": False,  # Disable for local testing
      "output_filename": 'task_assignment.json',
      "sampling_strategy": 'random',
      "labels_per_instance": 1,
      "instance_per_annotator": 10,
      "test_question_per_annotator": 0,
      "users": [],
    },

    "alert_time_each_instance": 10000000,
    "horizontal_key_bindings": true,

    "annotation_schemes": [
        {
            "annotation_type": "likert",
            "name": "Realism",
            "description": "How realistic is this scenario?",
            "labels": [
                { "name": "Least realistic", "key_value": '1' },
                { "name": "", "key_value": '2' },
                { "name": "", "key_value": '3' },
                { "name": "", "key_value": '4' },
                { "name": "Most realistic", "key_value": '5' }
            ],
            "label_requirement": {"required": True},
            "displaying_score": True,
        },
        {
            "annotation_type": "likert",
            "name": "Groundedness",
            "description": "How grounded is this scenario?",
            "labels": [
                { "name": "Least grounded", "key_value": '1' },
                { "name": "", "key_value": '2' },
                { "name": "", "key_value": '3' },
                { "name": "", "key_value": '4' },
                { "name": "Most grounded", "key_value": '5' }
            ],
            "label_requirement": {"required": True},
            "displaying_score": True,
        },
        {
            "annotation_type": "likert",
            "name": "Feasibility",
            "description": "How feasible is this scenario?",
            "labels": [
                { "name": "Least feasible", "key_value": '1' },
                { "name": "", "key_value": '2' },
                { "name": "", "key_value": '3' },
                { "name": "", "key_value": '4' },
                { "name": "Most feasible", "key_value": '5' }
            ],
            "label_requirement": {"required": True},
            "displaying_score": True,
        },
        {
            "annotation_type": "likert",
            "name": "Quality",
            "description": "How high-quality is this scenario?",
            "labels": [
                { "name": "Lowest quality", "key_value": '1' },
                { "name": "", "key_value": '2' },
                { "name": "", "key_value": '3' },
                { "name": "", "key_value": '4' },
                { "name": "Highest quality", "key_value": '5' }
            ],
            "label_requirement": {"required": True},
            "displaying_score": True,
            'has_free_response': {
               "instruction": 'Explain why you rated the Quality in the way that you did:',
               "required": True,
            },
        },
    ],

    "html_layout": "templates/scenario_layout.html",
    "surveyflow_html_layout": "default",
    "base_html_template": "default",
    "header_file": "default",
    "site_dir": "default"
}