{
    "token": '8THWeDcpopR8h5KiHpUDzcsM-Jj7ATazEYqsVVecviTn9Dv5Rai_y8aJHEUkmMptXr3psaGqegfiajHfVCXddXiHqwmTIg2braNd-v9Hd7-bPUL2xvV04yqs',
    "study_id": '684c803bca7c5923fb37eaa9',
    "max_concurrent_sessions": 10,
    "workload_checker_period": 60
}